### PR TITLE
feat: tracing, logging

### PR DESCRIPTION
**Pull request by Mukamik**

### CODE REVIEW

**Comment by Shabirmean** [comment]
:zap:  Release Status :zap: </br>
- **Version updated**: Version in the  has been updated to the next **minor** release version.
- **Publish Artifacts:** Check the most recent commit (ecb214df7a278bd46106796f6ad333420221d0b5) for correctness and run the ["pos-publish-release-artifacts"](https://console.cloud.google.com/cloud-build/triggers;region=global?project=point-of-sale-ci) trigger against this branch **[release-minor]** to upload the artifacts _(Jars and Images)_ to Artifact registry.

**Comment by Shabirmean** [comment]
:zap:  Release Status :zap: </br>
- **Version updated**: Version in the  has been updated to the next **minor** release version.
- **Publish Artifacts:** Check the most recent commit (7b0e1f8789fdf840ff7beafdd9ccd7694fa6c18e) for correctness and run the ["pos-publish-release-artifacts-jss"](https://console.cloud.google.com/cloud-build/triggers;region=global?project=point-of-sale-ci) trigger against this branch **[release-minor]** to upload the artifacts _(Jars and Images)_ to Artifact registry.

**Review by NimJay — APPROVED** [review]
The file changes are analogous to those from https://github.com/GoogleCloudPlatform/point-of-sale/pull/135.

And all CI is passing.

Approved.

Thanks, @Mukamik! :)

**Comment by Shabirmean** [comment]
:zap:  Release Status :zap: </br>
- **Artifacts published**: [Maven JARs and Container images](https://console.cloud.google.com/artifacts/browse/point-of-sale-ci?project=point-of-sale-ci) for release version **v0.3.0-jss** have been published to Artifact Registry
- **Manifests updated**: [Release manifests](https://github.com/GoogleCloudPlatform/point-of-sale/tree//k8-manifests/release) have been updated to use the version **v0.3.0-jss** images
- **Version bumped:** Version in the _pom.xml/package.json_ has been bumped () to the snapshot version of the next **patch** release **v**
- **Github release created:** A draft [Github release](https://github.com/GoogleCloudPlatform/point-of-sale/releases) has been created. Inspect and **publish it**
- **Merge PR:** Inspect the latest changes and merge the PR to **main** to complete the release.

:rocket: Don't forget to run the ["pos-deploy-release"](https://console.cloud.google.com/cloud-build/triggers;region=global?project=point-of-sale-ci) trigger against the **main** to deploy the latest release!!!

**Comment by Shabirmean** [comment]
:zap:  Release Status :zap: </br>
- ~~**Artifacts published**: [Maven JARs and Container images](https://console.cloud.google.com/artifacts/browse/point-of-sale-ci?project=point-of-sale-ci) for release version **v0.3.0-jss** have been published to Artifact Registry~~
- **Manifests updated**: [Release manifests](https://github.com/GoogleCloudPlatform/point-of-sale/tree//k8-manifests/release) have been updated to use the version **v0.3.0-jss** images
- **Version bumped:** Version in the _pom.xml/package.json_ has been bumped () to the snapshot version of the next **patch** release **v**
- **Github release created:** A draft [Github release](https://github.com/GoogleCloudPlatform/point-of-sale/releases) has been created. Inspect and **publish it**
- **Merge PR:** Inspect the latest changes and merge the PR to **jss** to complete the release.

:rocket:

**Pull request merged**
