### PR TITLE
chore: move from Cloud KMS to Cloud Secrets

### PR DESCRIPTION
**Pull request by Shabirmean**
Use Secrets manager instead of Cloud KMS

### CODE REVIEW

**Comment by Shabirmean** [comment]
Openned issue https://github.com/GoogleCloudPlatform/point-of-sale/issues/210 and closing this PR until we get resolution for the bug mentioned in that PR

**Comment by Shabirmean** [comment]
:zap:  Two deployments have been created for the Point-of-Sale application. You may access and test them at: :zap: </br>
- **MySQL DB** backed deployment: [**34.170.81.128**](http://34.170.81.128)
- **Embedded H2** DB backed deployment: [**34.27.45.66**](http://34.27.45.66)

**Comment by Shabirmean** [comment]
:zap:  Two deployments have been created for the Point-of-Sale application. You may access and test them at: :zap: </br>
- **MySQL DB** backed deployment: [**34.170.81.128**](http://34.170.81.128)
- **Embedded H2** DB backed deployment: [**34.27.45.66**](http://34.27.45.66)

**Review by minherz — APPROVED** [review]
lgtm;
nit: is it correct to assume that these environment variables are defined locally within Cloud Build configuration?

**Comment by Shabirmean** [comment]
> lgtm; nit: is it correct to assume that these environment variables are defined locally within Cloud Build configuration?

Yup. That's correct

**Comment by Shabirmean** [comment]
:zap:  Two deployments have been created for the Point-of-Sale application. You may access and test them at: :zap: </br>
- **MySQL DB** backed deployment: [**34.170.81.128**](http://34.170.81.128)
- **Embedded H2** DB backed deployment: [**34.27.45.66**](http://34.27.45.66)

**Pull request merged**
