### PR TITLE
cleanup: update distroless image 

### PR DESCRIPTION
**Pull request by mathieu-benoit**
Based on [this doc from `Jib`](https://github.com/GoogleContainerTools/jib/blob/master/docs/default_base_image.md#migration-from-pre-30):
> However, even when you decide to keep using Distroless, at least we strongly recommend gcr.io/distroless/java-debian10:11, because, as of Apr 2021, gcr.io/distroless/java:{8,11} is based on Debian 9 that reached end-of-life. (Note gcr.io/distroless/java-debian10 doesn't have :8.)

And when looking at the [`distroless` repo](https://github.com/GoogleContainerTools/distroless/tree/main/java), there is even this [new update/recommendation since 2021-12](https://github.com/GoogleContainerTools/distroless/commit/d4ef1e32e0bdbf694f20b69f71766d72b1adc667#diff-0c997611c3c5fb9fa0641cb88e5aaa485b5fbc7293676fc28afab310dd430812) hence this update with `gcr.io/distroless/java11-debian11`.

### CODE REVIEW

**Comment by Shabirmean** [comment]
@mathieu-benoit - were you able to run and test it with this image?

**Comment by mathieu-benoit** [comment]
Sorry, meant to set this PR as Draft in order to continue my tests. Just did, and will report back here once tested.
Furtermore, there is this `conventionalcommits.org` asking me rename my commit, could we by-pass this or do you want me to proceed?

**Comment by Shabirmean** [comment]
> Sorry, meant to set this PR as Draft in order to continue my tests. Just did, and will report back here once tested. Furthermore, there is this `conventionalcommits.org` asking me rename my commit, could we by-pass this or do you want me to proceed?

I think for now it's okay since I know the changes. In future making the commits in the conventional commit format should fix it. Also the PR title should follow conventional commit style. I have changed the title for now

```sh
<small_tag>: <description>

examples:
fix: fixed somthing
cleanup: clear gitignore
doc: updated the readme
release: releasing new version
```

**Comment by mathieu-benoit** [comment]
Oh ok gotcha, thanks. Out of curiosity, any automatic check/control for the PR's title convention? Or developer guide entry (sorry if I missed it)? Which could help any future contributor?

**Comment by Shabirmean** [comment]
> Oh ok gotcha, thanks. Out of curiosity, any automatic check/control for the PR's title convention? Or developer guide entry (sorry if I missed it)? Which could help any future contributors and avoid this error?

I think in general the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) guide shall be useful

**Comment by mathieu-benoit** [comment]
FYI: I was able to test it with `inventory` and `payments`, working succesfully. But I'm not able to build a new image for `api-server` because of this issue #70.

**Comment by mathieu-benoit** [comment]
Hey @Shabirmean, leave it to you to decide but I think it's safe to merge this PR as I was able to test it with `inventory` and `payments`, we may want to assume that i's working with `api-server`, sorry not able to confirm with the latter because of #70.

**Review by Shabirmean — APPROVED** [review]

**Pull request merged**
