### PR TITLE
bug: fix CI error for GitHub CLI

### PR DESCRIPTION
**Pull request by Shabirmean**
### Description
- The last cloudbuild step in the CI failed for renovate PRs
- The step was using `gh` CLI to add comments to the PRs
- The reason for failure was because it was using the cloudbuilds **substitution variable**, **_HEAD_REPO_URL**. 
- This variable was pointing to the forked repo of renovate than this origin repo
- The forked repo does not have a PR openned - so it failed

### Changes
- Update the cloudbuild files to use this repo as the source

### CODE REVIEW

**Comment by Shabirmean** [comment]
#:zap:  Two deployments have been created for the Point-of-Sale application. You may access and test them at: :zap: </br>
#- **MySQL DB** backed deployment: [****](http://)
#- **Embedded H2** DB backed deployment: [****](http://)
Test

**Review by charlieyu1996 — DISMISSED** [review]
LGTM

**Review by bourgeoisor — APPROVED** [review]
Wow good catch-- I don't typically like hard-coded value but this is fine to unblock!

**Comment by Shabirmean** [comment]
:zap:  Two deployments have been created for the Point-of-Sale application. You may access and test them at: :zap: </br>
- **MySQL DB** backed deployment: [**34.121.146.65**](http://34.121.146.65)
- **Embedded H2** DB backed deployment: [**34.122.31.191**](http://34.122.31.191)

**Comment by Shabirmean** [comment]
:zap:  Two deployments have been created for the Point-of-Sale application. You may access and test them at: :zap: </br>
- **MySQL DB** backed deployment: [**34.121.146.65**](http://34.121.146.65)
- **Embedded H2** DB backed deployment: [**34.122.31.191**](http://34.122.31.191)

**Pull request merged**
